### PR TITLE
Added missing check for NaN

### PR DESCRIPTION
**Pull request by txgruppi**

### CODE REVIEW

**Comment by andreyvital** [comment]
What's the default behavior of node emitter when event cannot be bound? Isn't a good deal throw something? I'd always like throw something. :smile:

**Comment by txgruppi** [comment]
In which case it will not be bound?

**Comment by andreyvital** [comment]
Anything that isn't string or numeric will do. Thoughts?

**Comment by txgruppi** [comment]
Anything that isn't a valid integer will be used as string. Converted by JS when used as key.

**Pull request closed without merging**
